### ISSUE TITLE
Add vulkan_scene_graph_widget 

### ISSUE THREAD

**Issue by takev** [hikogui/hikogui#294]
A sub-class of blank_widget, designed to integrate easily with [VulkanSceneGraph](https://github.com/vsg-dev/VulkanSceneGraph).

This widget should be designed to be easily subclass

**Comment by shujaatak** [comment]
That would be great!

**Comment by shujaatak** [comment]
In my opinion, this feature will immensely benefit both 3D developers and ttauri project itself. I truely like the ttauri project's Low Latency so like me many other developers would definitely like to move from imgui to ttauri. 
Waiting for vulkan_scene_graph integration impatiently!

**Comment by takev** [comment]
I hope someone will pick this up. Currently I have other parts of the project on my priority list: the how-to-draw release, followed by audio. I am only one man.

**Comment by shujaatak** [comment]
I appreciate what you already have shared with us! Much love!
