### ISSUE TITLE
canvas api

### ISSUE THREAD

**Issue by bizehao** [hikogui/hikogui#307]
Why not provide a set of canvas API? It's very convenient to customize the view

**Comment by takev** [comment]
If you mean the Canvas API following: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API
It would be too slow (uses lots of CPU time/power) for drawing widgets.

However you can draw paths onto a cache-image, then display those cache-images using the image-pipeline.

**Comment by takev** [comment]
ttauri already has skia-like canvas. It is `graphics_path` this allows drawing vector graphics then stamp those onto a pixmap. The pixmap can then be displayed through the image pipeline.

This used to be the standard way of displaying stuff on the screen.

But the new box- & sdf-pipelines are few orders of a magnitude faster, as they are hardware accelerated.

**Comment by bizehao** [comment]
ok，I will try to compile it tonight
