### ISSUE TITLE
Current vulkan SDK is incompatible

### ISSUE THREAD

**Issue by takev** [hikogui/hikogui#379]
'createResultValue': is not a member of 'vk'.

**Comment by jakoch** [comment]
Upstream Issue: https://github.com/KhronosGroup/Vulkan-Hpp/commit/16a44bb94ffb48de6e64b18e39222fd836b66056
The bugfix landed in v1.3.217.0. 
This version is not yet released on the SDK website, but i [requested](https://vulkan.lunarg.com/issue/view/62aa6e575df112ce7405d1f3) it.

**Comment by takev** [comment]
Removed createResultValue usage from hikogui, actually resulted in simpler and less code.
