### ISSUE TITLE
Replace CAExcludePath environment variable with command line options.

### ISSUE THREAD

**Issue by takev** [hikogui/hikogui#504]
https://devblogs.microsoft.com/cppblog/customized-warning-levels-and-code-analysis-for-external-headers/

**Comment by jakoch** [comment]
Yes, CAExcludePath is set as a static path for "_deps" currently ([see](https://github.com/hikogui/hikogui/blob/72158c0ff7e736339d016628c43b4b5857c3085b/CMakeLists.txt#L317)).

We could set this via the new CMakePresets as environment var with [macro expansion](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#macro-expansion). 
That allows to use dynamic paths, e.g. `${sourceDir}/out/${presetName}`:
```
    {
      "name": "windows-ana",
      "description": "....",
      "inherits": [
        "...",
        "..."
      ],
      "environment": {
        "caexcludepath": "C:/VulkanSDK;C:/Program Files;${sourceDir}/out/${presetName}/_deps"
      }
    },
```

**Comment by takev** [comment]
You can use the command line now as well for these paths, so you can do it within CMakeLists.txt
this means we compute the VulkanSDK path and other dependencies as CMake knows those paths.

I think there is a special option to exclude system headers as well.
