### ISSUE TITLE
gui_window_win32::get_keyboard_modifiers narrow_casts short 0x8000 (-32767) to uint16_t, failing the assertion in narrow_cast

### ISSUE THREAD

**Issue by ryanjsims** [hikogui/hikogui#522]
When writing a vulkan widget for a model viewing/exporting program I'm working on, I noticed that tapping the shift key in a Debug build caused the program to crash. After debugging, it appears that the culprit is [gui_window_win32_impl.cpp:564](https://github.com/hikogui/hikogui/blob/30a5daf87a03819fcae53ce086462dd48ab0ae5b/src/hikogui/GUI/gui_window_win32_impl.cpp#L564), where the WinApi function GetAsyncKeyState returns a signed short 0x8000 (-32767) if a modifier key is held, which is promptly narrow_cast to a uint16_t, failing narrow_cast's assert.

The same problem occurs for the other narrow_casts in the same function.

**Comment by takev** [comment]
I see, thanks.
I can fix that easy. I may add a special signed_cast, unsigned_cast functions that do not change size.

**Comment by takev** [comment]
It was very weird how I never triggered this bug, not sure what to say about that.
Anyway I have a fix, I will merge it in main as soon as the CI validates it.

Is it going well with your model-view project?
