### ISSUE TITLE
Problems trying out the library

### ISSUE THREAD

**Issue by kamrann** [hikogui/hikogui#529]
I wanted to take a quick look at the library to see if it may suit my needs, but ran into some issues.

First off, I'd suggest to perhaps set the default branch to something more stable, since `main` appears to have diverged from the installation instructions. I had no `MSVC x64 Debug` configuration, but quite a lot of other ones that gave either configuration or compilation errors.

Having switched to `v0.7.0`, the build went fine (on latest VS preview). However the various demos are all crashing with the below error:
![image](https://github.com/hikogui/hikogui/assets/2475657/469c161e-f540-4fb0-a137-e0e835f4e8fb)

**Comment by takev** [comment]
I will fix the installation instructions. And I will need to figure out why `acquireNextImageKHR()` fails; which graphics card are you using? It is interesting that you did get a window and widgets are being displayed, which means `acquireNextImageKHR()` did succeed at least once.

Sadly MSVC and Visual Studio are extremely buggy, so you often see compilation errors from version to version.

Right now for example having "buildPresets" in CMakePresets.json will break builds where the compiler is unable to find the system headers. This is of course already reported, but it means that main does not work anymore.

But also MSVC is the only compiler that implements enough of C++20 that it can compile HikoGUI, so we are a bit stuck. I had no idea it would take this long for clang and gcc to catch up, but they are still not finished with it.

**Comment by takev** [comment]
It looks like adding the following case label to the switch underneath vulkan_device().acquireNextImageKHR() in gfx_surface_vulkan_impl.cpp:142, may possibly solve the issue.

It seems **not-ready** is still a successful result of that function, and HikoGUI should automatically block on the not-ready image until it is ready (through the semaphore that is passed to the acquireNextImageKHR() function).

```
    case vk::Result::eNotReady:
        // We acquired the next frameBufferIndex, but this swapchain image is
        // not yet ready, we need to wait for the imageAvailableSemaphore.
        return {frameBufferIndex};
```

**Comment by kamrann** [comment]
I'm using a 1080Ti. It is in an external housing which adds a bit of latency, but I wouldn't expect that to make all that much of a difference. Is there any easy way for me to control which graphics device is being used by the demos?

I just tried the bugfix branch, and rather than crash it now seems to just hang indefinitely. So it seems that for whatever reason, the frame result is never completing. I've attached a minidump. 

And yeah, it seems to be non-deterministic. The `RelWithDebugInfo` build seems to always render the UI then immediately hit the issue, whereas `Debug` build generally works for a bit - I can interact with things - but at some point before long will hit the same thing.

As for the compilation problems, yeah I have the same thing. I'm trying to keep a project always building with both MSVC and Clang, but it's a balancing act between workarounds for missing features in Clang vs workarounds for bugs in MSVC. In particular it seems to have regressed in the last year or two, I'm getting increasingly frequent name lookup bugs in nested lambda/template contexts...
[hikogui_demo_dump.zip](https://github.com/hikogui/hikogui/files/11884387/hikogui_demo_dump.zip)

**Comment by takev** [comment]
I am not setup to handle mini-dumps at the moment.

Could you maybe send me the output from the hikogui_demoi.exe instead?
The output contains a lot of information about how Vulkan is configured for a specific window.
Maybe there is something interesting about the swap-chain that is different from my computer.

I am also using an nvidia card. What version of the driver are you using?

**Comment by kamrann** [comment]
Ah, I should have looked at that! There's an error there at the end which is no doubt related to the problem.

[hikogui_demo_output.txt](https://github.com/hikogui/hikogui/files/11884855/hikogui_demo_output.txt)

![image](https://github.com/hikogui/hikogui/assets/2475657/dfc372a7-9733-4cbc-85e1-6fb94b32a018)

**Comment by takev** [comment]
I am not sure which graphics card is actually selected, it look like the Radeon RX Vega on your system may have been selected instead.

I need to look if I can the logs to show which device was actually selected :-).

The validation errors means there is a bug in HikoGUI, I will see if I can reproduce those. In debugging mode that Vulkan API checks if it is being used correctly these are the validation errors.

**Comment by kamrann** [comment]
If this is being decided by Vulkan (rather than HikoGui) then I'd be surprised if that was the case. It's always selected the GeForce when it's connected so far as I'm aware - when I'm working with Unreal for example.

Are you saying there is some additional log output somewhere that you want me to upload? I can also debug it if this could be determined by doing so, if you're able to tell me where to look.

**Comment by takev** [comment]
Nah, I need to add more logging to HikoGUI to show which graphics card was selected.
Possible I need to install a new SDK to get the same validation errors. I will look tomorrow it is getting late.

Graphic Card selection is weird. In Vulkan every graphics card will work with any display, so we need to find the best one.
HikoGUI tries to score graphics card and selects the best one. It gives higher scores to discrete GPU and GPUs with swap-chains of specific color mode, depth, swapchain-types.

On your computer the nvidia and ATI get the same score 23, the intel GPU gets 22.

I probably need some kind of system for application developers to score a GPU, desktop applications probably should use the one that uses the least amount of power, unless you specifically need to do something intensive.

And we need a way for a user to select a GPU at runtime. I did write HikoGUI to make it possible to switch out the device, but I don't have a computer with multiple GPUs, so never really tried that.

**Comment by kamrann** [comment]
Understood. Yeah ok, if HikoGUI is doing the scoring itself then of course it may have chosen the Radeon. In terms of compute power my devices are very different (GeForce >> Radeon >> Intel), but as you say, for 2D UI stuff the considerations are very different from intensive 3D.

**Comment by takev** [comment]
Also at the time, and also right now, I have not found a way to select a GPU in any other way then scoring it myself.

There seem to be no API on windows or in Vulkan to get the correct GPU, whatever that may mean. At best I could maybe found out what GPU is driving the display, but I am guessing on your computer that would actually be the intel device.

I did learn a trick just now that possibly the highest performance GPU is the one with the most memory, as new generation GPUs get more and more memory.

**Comment by kamrann** [comment]
Yeah can't help much there I'm afraid, I have no idea how OSs are generally dealing with having multiple active GPUs. Certainly from the little I've read about Vulkan, it seems very low level so not surprised it doesn't make any decisions for you. The last time I did any work directly using a graphics API it was DirectX either 7 or 8, so I'm a little out of date!

**Comment by takev** [comment]
I have changed the switch statement again and let eNotReady return to the main-loop waiting for the next vsync.

The validation errors that you saw where about the semaphore not being attached to something that could trigger it. i.e. the next-image call did not return a image when eNotReady happened. I found some more documentation from Vulkan that was a little bit more clear about that. Hopefully this works now.

I also started work on selecting a better graphics card based on the graphic-card ordering from DirectX. So hopefully DirectX will select the same graphics card as most games would by default do. I also want to add the ability for the user to select a graphics card.

**Comment by kamrann** [comment]
Yep, that change looks to have fixed the freezing problem. I notice that it is quite frequently hitting `eNotReady` still, especially in `Debug` config. Forgive me if I'm misunderstanding, but does this imply that it's now dropping frames when this happens? It seems a little strange if so even for `Debug` mode, given the simplicity of the example UI.

Anyway, I'm able to experiment a bit now. Thanks!

**Comment by takev** [comment]
Debug mode because of the number of checks I inserted is about 100x slower than a release build.

However eNotReady is the reverse of dropped frames. The application is ready to draw another frame, but the GPU does not have one yet.

However since it now has to loop back to vsync, it could now be skipping frames, it seems odd. We could use triple buffering to see if that fixes things. I think the difference is between different GPUs which of the calls block, getnextimage() or submitimage().

**Comment by takev** [comment]
I can add some counters to see  the ratio of eNotReady vs eSuccess.
counters are a pretty low resource thing, just an atomic increment on a global variable.

**Comment by kamrann** [comment]
Yeah, I'm not actually noticing any obvious latency/drawing issue, but still probably worth keeping an eye on. Seems especially strange for it to be more common in debug builds if it's caused by the GPU lagging behind the CPU, unless debug build is also enabling some different behaviours on the GPU? Instinctively I'd expect the opposite.

**Comment by takev** [comment]
Debug build does insert RenderDoc and the validation layers into Vulkan. Maybe that changes how Vulkan commands are processed? It's weird.
