### ISSUE TITLE
Incorrect spelling of 'defined' in macro definition

### ISSUE THREAD

**Issue by jonah766** [hikogui/hikogui#593]
https://github.com/hikogui/hikogui/blob/b002b81050c544dadf928000a532f89d5d773739/src/hikogui/macros.hpp#L49

In the linked code snippet there is a typo on the use of the `defined()` macro, instead spelling it as `defeind()`.

Presumably this hasn't come up as an error in compilation as that platform hasn't been targeted during testing.

**Comment by takev** [comment]
Thanks, I would not have found that.
