### ISSUE TITLE
Improve IDE support by providing CMakePresets.json

### ISSUE THREAD

**Issue by jakoch** [hikogui/hikogui#65]
This is an upcomming change to the currently used `CMakeSettings.json` approach, which is specific to Visual Studio.
The new `CMakePresets.json` file will be used by IDEs to pickup and provide the configuration presets to the users.

**VS**
Visual Studio will switch to this new config file format, see [VS Roadmap](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-roadmap#c).
It will replace `CMakeSettings.json` which had [some issues](https://gitlab.kitware.com/cmake/cmake/-/issues/21164).

**VS Code**
Visual Studio Code is [switching](https://github.com/microsoft/vscode-cmake-tools/issues/529).

Presets are available in CMake v3.19+.
- https://cmake.org/cmake/help/latest/guide/ide-integration/index.html#presets
- https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#id1

#### Todo
- [ ] remove the VS specific `CMakeSettings.json`
- [ ] setup `CMakePresets.json`
  - The file should provide reasonable defaults to configure the build environment for ttauri for multiple IDEs.

**Comment by takev** [comment]
The newest Visual Studio 2022 is by default configured to read CMakePresets.json if available.

**Comment by jakoch** [comment]
I worked on this issue quite a bit, but CMakePresets.json is insanely broken for Visual Studio Code.
Last time i checked, it didn't even set the CMake `-A` (arch) and `-G` (generator) correctly.
But, of course, we can try it with VS2022. Maybe we get it working.
