### ISSUE TITLE
failed to compile hikogui as a CMake subdirectory.

### ISSUE THREAD

**Issue by Anesthesia4** [hikogui/hikogui#668]
i use hikogui as a CMake submodule, with the following settings
set(HI_ENABLE_MODULES OFF CACHE BOOL "Enable modules" FORCE)
set(BUILD_SHARED_LIBS ON CACHE BOOL "Build shared libraries" FORCE)
set(BUILD_EXAMPLES OFF CACHE BOOL "Build examples" FORCE)
then use
target_link_resources(${PROJECT_NAME} hikogui)
target_include_directories(${PROJECT_NAME} PUBLIC hikogui)
it generated the project solution, but it did not compile, the compiler said that it could not find some header files.
And I can't include "hikogui/hikogui.hpp" in my project.

here's the log:
third_party\hikogui\examples\custom_widgets\custom_widget_drawing_example_impl.cpp(5): fatal error C1083: “hikogui/hikogui.hpp”: No such file or directory
third_party\hikogui\examples\codec\json_to_bon8_impl.cpp(5): fatal error C1083: “hikogui/hikogui.hpp”: No such file or directory
third_party\hikogui\examples\custom_widgets\custom_widget_with_child_example_impl.cpp(5): fatal error C1083: “hikogui/hikogui.hpp”: No such file or directory
......
third_party\hikogui\mod\hikogui\SIMD\native_i32x4_tests.cpp(5): fatal error C1083: “native_i32x4_sse2.hpp”: No such file or directory
third_party\hikogui\mod\hikogui\SIMD\simd_tests.cpp(5): fatal error C1083: “simd_intf.hpp”: No such file or directory
third_party\hikogui\mod\hikogui\algorithm\algorithm_misc_tests.cpp(5): fatal error C1083: “algorithm_misc.hpp”: No such file or directory

**Comment by takev** [comment]
Ah, I think that is because some of the header files are not listed in CMakeList_headers.txt.
I still don't really have a tool to check if every header is listed there, it should be a CI check.

I will take a look at that. Sadly I can not do this quickly, maybe saturday, sunday or monday.

**Comment by takev** [comment]
Except it is weird that hikogui/hikogui.hpp itself is missing. Maybe something else is going wrong.

**Comment by takev** [comment]
Also you need to use:
   target_link_libraries(${PROJECT} PRIVATE hikogui::hikogui)

You may also use PUBLIC. The target_include_directories() should not be part of it.

**Comment by Anesthesia4** [comment]
Thank you for your reply! I'll give it a try.

**Comment by Anesthesia4** [comment]
Regarding adding code files to a CMake project, I've used something like traversing an entire folder to add project files to a project before, and filtering for specific platforms by determining the name of the folder, so this might be a good way to do it.

**Comment by Anesthesia4** [comment]
I tried to change to hikogui::hikogui, CMake says it can't find hikogui::hikogui, PUBLIC and PRIVATE don't work😢

**Comment by takev** [comment]
Okay thanks. I will change the hikogui/hello_world to also have the ability to use hikogui as a git-submodule. And see what kind of things go wrong with that.

**Comment by Anesthesia4** [comment]
Sorry for misrepresenting my problem, I'm not using hikogui as a git submodule, but rather I'm using CMake add_subdirectory to add hikogui

**Comment by Anesthesia4** [comment]
I'm sorry it took me so long to find this bug, I realized that a function I wrote earlier to iterate through all the files in a folder was written incorrectly, here is the wrong code:

function(retrieve_files path out_files)
    set(source_list)
    message(STATUS "Retrieving files in ${path}")

    # That's the problem, he's traversing all the files under the current module, including hikogui.
    file(GLOB_RECURSE HEAD_FILES RELATIVE ${path} CONFIGURE_DEPENDS *.h *.hpp *.ini)

    # same
    file(GLOB_RECURSE SRC_FILES RELATIVE ${path} CONFIGURE_DEPENDS *.cpp *.c *.ixx)

    set(ALL_FILES ${HEAD_FILES} ${SRC_FILES})
    ...other code...
endfunction()

Here is the modified:
function(retrieve_files path out_files)
    message(STATUS "Retrieving files in ${path}")

    # header files .h .hpp. ini
    file(GLOB_RECURSE HEAD_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} CONFIGURE_DEPENDS ${path}/*.h ${path}/*.hpp ${path}/*.ini)

    # source files *.cpp *.c
    file(GLOB_RECURSE SRC_FILES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} CONFIGURE_DEPENDS ${path}/*.cpp ${path}*.c ${path}*.ixx)

    # append to ALL_FILES
    set(ALL_FILES ${HEAD_FILES} ${SRC_FILES})

    set(RESULT "")

    foreach(fileItem ${ALL_FILES})
        # Get the directory of the source file
        get_filename_component(PARENT_DIR "${fileItem}" DIRECTORY)

        if(PARENT_DIR STREQUAL "windows")
            if(WIN32)
                set(RESULT "${RESULT};${fileItem}")
            else()
                continue()
            endif()
        elseif(PARENT_DIR STREQUAL "linux")
            if(UNIX AND NOT APPLE)
                set(RESULT "${RESULT};${fileItem}")
            else()
                continue()
            endif()
        elseif(PARENT_DIR STREQUAL "mac")
            if(APPLE)
                set(RESULT "${RESULT};${fileItem}")
            else()
                continue()
            endif()
        else()
            set(RESULT "${RESULT};${fileItem}")
        endif()
        
        # Remove common directory prefix to make the group
        string(REPLACE "${path}" "" GROUP "${PARENT_DIR}")
        # Make sure we are using windows slashes
        string(REPLACE "/" "\\" GROUP "${GROUP}")
        # Group into "Source Files" and "Header Files"
        set(GROUP "${GROUP}")
        source_group("${GROUP}" FILES "${fileItem}")
    endforeach()

    set(${out_files} ${RESULT} PARENT_SCOPE)
endfunction()

**Comment by takev** [comment]
I am glad you figured it out.

I did follow your suggestion to generate the CMakeLists_include.cmake that is now part of main. I am also updating how the hikogui-hello-world is build.

You should be able to use the standard target_link_libraries() for hikogui::hikogui (I now added the alias for that). I changed that because of modules, but cmake should now handle libraries-as-modules, so hopefully that will be fine.

You still need to add the resources from hikogui into your application. Using the `target_link_resources()` function, which is a custom function, not sure how to export this function properly, yet.

**Comment by Anesthesia4** [comment]
I tried hikogui in the main branch, and it works fine, thanks!
