### ISSUE TITLE
More layouts?

### ISSUE THREAD

**Issue by Anesthesia4** [hikogui/hikogui#678]
I am writing a slider widget. I want to display the current value in the center of the slider, is there any way to do this? Like a center_layout?

**Comment by takev** [comment]
You can set the alignment of a label widget to horizontal_alignement::center.

At least this is for now, I am planning on adding .css style theming, so in the future you will add something like ".center" to the constructor of the label widget.

**Comment by Anesthesia4** [comment]
I use the following code to center the text control: std::make_unique<hi::text_widget>(this, _value_txt, hi::alignment::middle_center());
But it looks at top_center.
![image](https://github.com/hikogui/hikogui/assets/45580096/0b99fd6b-0bab-4017-aaea-4d3d05e00e50)
and here is set_layout():
void set_layout(hi::widget_layout const &context) noexcept override {
       if (hi::compare_store(_layout, context)) {
           _value_text->set_layout(context.transform(context.shape, hi::transform_command::level));
       }
    }

**Comment by takev** [comment]
You can use a grid layout. You may also want to look at the implementation of label_widget. It shows how a grid_layout can be used inside a widget (a label is a text + icon).

In case of your slider widget. You can use a grid layout to make 2 rows, 1 column. In the top row you place a text_widget and the bottom part you directly draw the slider.

**Comment by takev** [comment]
I am not sure if you can align a text_widget in the way you think it does. I have to rebuild the text_widget completely.

Can you try the label_widget instead and use either top_center() or bottom_center() (middle_center() does a weird thing where it draws the icon on top of the label)?

**Comment by Anesthesia4** [comment]
Ok, I will try to use label_widget. and i just went and wrote some test code to display the label_widget, and it does have the layout I want!
![image](https://github.com/hikogui/hikogui/assets/45580096/1df9aa24-6bfc-4c96-9c20-29d04b1e00cf)

**Comment by Anesthesia4** [comment]
I finished the feature, thanks you!

**Comment by takev** [comment]
Okay, top alignment will put the text's 'x' character aligned with the top of the layout. That means the larger characters like 'f' will have their ascender into the margin. This makes it possible to pack more small widgets vertically, as the text next to a small widget will share the margin between them for the ascenders and descenders.

If you want margin around the text you will need to add an internal margin. The selection_widget is an example where I add margins inside the visible border of the selection widget.

The grid layout can help here, as it can have margins between cells, so you can have a little space between the text and the slider graphics.

**Comment by Anesthesia4** [comment]
When I changed to hi::alignment::middle_center() is what I wanted
