### ISSUE TITLE
what about the new layout system

### ISSUE THREAD

**Issue by Anesthesia4** [hikogui/hikogui#682]
Hello, takev. I've been learning hikogui for a while now, and the layout system is the one that makes me feel the most uncomfortable using it, because he's not intuitive enough. For example, if I want to combine some widgets to make a new widget, I have to create a new class myself and use the layout calculator class to layout the widget. I wonder if the layout of the widgets could be managed by something like a "slot" into which all the widgets fit, and then the size and position of the controls would be controlled by the "slot", which would make it easy to control the size and position of the widgets and to write declarative layout code. Each of these widgets can also hold one or more slots, or no slots. For example, the button, it is only a "slot", the slot has some configuration items, such as alignment, padding and so on. This makes it easier to layout widgets.

**Comment by takev** [comment]
With the layout calculator you mean the grid-layout?

You can also add a grid-widget as a child of your class and put all your other child widgets into the grid, which is slightly easier I guess.

But maybe we can improve the API of the grid-layout, to make it easier to put widgets in it as children.

**Comment by Anesthesia4** [comment]
Yes, I'm talking about the grid layout. It's not easy enough for developers to use this part. My idea is that each part needs to be placed inside a slot, then the part can manage the layout of the slot by providing different layout container widgets (e.g. horizontal layout containers), and then different types of slots can have different states, and then the layout containers manage the layout based on the current state of the slot.
In this way, we can build a tree of widgets so that children() can be hidden as well

**Comment by takev** [comment]
I was just thinking of the following.

```cpp
// 2 columns, 4 rows, the my_widget as the first argument is so that managed_widget can find templated methods.
class my_widget : public hi::managed_widget<my_widget, 2, 4> {
    // If you add this specialisation it will manage the returned child widget completely, and put it into column A, row 1.
    template<> auto make_child_widget_at<"A1">()
    {
        return std::make_shared<hi::label_widget>(this, tr("my text"));
    }

    // If you want to put a drawing in cell B2 you have to define at least the draw_at function.
    template<> void draw_at<"B2">(auto &cell, draw_context const &context)
    {
       // Do your drawing here, the context is already placed in the correct position. You can access layout
       // information from cell, and also data that you want to keep there.
    }

    // Optional: if you want it to manage data for this cell.
    template<> auto data_at<"B2">()
    {
        return my_type_for_just_this_cell{intialized};
    }

    // Probably still required for your cell to return a minimum, maximum size and margins.
    template<> box_constraints update_constraints_at<"B2">(auto &cell)
    {
        return {50, 25};
    }

    // Optional: gives you the opportunity to pre calculate layout and store it in the cell's data.
    template<> void set_layout_at<"B2">(auto &cell, widget_layout const &context)
    {
        cell.data.foo = context.width() / 2.0f;
    }
};
```

**Comment by Anesthesia4** [comment]
I think an object-oriented approach would be better:
```
class slot {
public:
    hi::widget* content; // the widget that is in the slot
    size_rule _rule; // the size rule of the slot, e.g. content size, fill
    bool _some_parameter; // some parameter that is specific to the slot
    slot& rule(size_rule in_rule) {
        _rule = in_rule;
        return *this;
    }
    slot& some_parameter(bool in_some_parameter) {
        _some_parameter = in_some_parameter;
        return *this;
    }
    slot& operator[](hi::widget* in_content) {
        content = in_content;
    }
};

// This is a leaf widget, it doesn't have any children
class leaf_widget : hi::widget {
    // This is the draw function, it is called when the widget needs to be drawn
    void draw(hi::draw_context const& context) noexcept override;
};

// This is a compound widget, there is only one slot
class compound_widget : hi::widget {
protected:
    slot _child_slot; // the slot that contains the child widget
};

// This is a composite widget, it has children
class composite_widget : hi::widget {
public:
    slot& operator+(slot& in_slot) {
        _child_slots.push_back(in_slot);
        return in_slot;
    }
protected:
    std::vector<slot> _child_slots; // the slots that contain the child widgets
};

class vertical : public composite_widget {
public:
    class vertical_slot : public slot {
        horizontal_alignment _alignment; // the alignment of the slot
        padding _padding;
    };
};

class horizontal : public composite_widget {
public:
    class horizontal_slot : public slot {
        vertical_alignment _alignment; // the alignment of the slot
        padding _padding;
    };
};

class my_widget : public compound_widget {
    my_widget() {
        _child_slot[
            new vertical()
            +vertical::vertical_slot()
            [
                new leaf_widget()
            ]
        ]
        .some_parameter(true)
        .rule(size_rule::fill);
    }
};

```

**Comment by Anesthesia4** [comment]
and the vertical and horizontal internal implementations can still be grid-layout

**Comment by takev** [comment]
The grid-layout algorithm already has slots that you can use with your own slot-type.

The type is completely opaque to the algorithm, so you can do what you want, including what you suggest. The grid-layout widgets uses it for child widgets, while some other widgets use an enum to figure out what to draw (you almost never want just child widgets).

If you want a compound widget then you can have a grid-widget as a child and add the other widgets inside that grid-widget.

The problem I have with making an inheritance hierarchy of widgets is that it violates so many rules of software design; and I already fell into those traps before, in-fact with these same widgets.
